-- CreateTable
CREATE TABLE "Book" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "isbn" TEXT,
    "title" TEXT NOT NULL,
    "originalTitle" TEXT,
    "subtitle" TEXT,
    "author" TEXT NOT NULL,
    "authorLastFirst" TEXT,
    "translator" TEXT,
    "publisher" TEXT,
    "genre" TEXT,
    "status" TEXT NOT NULL,
    "coverUrl" TEXT,
    "description" TEXT,
    "publishedDate" TEXT,
    "yearPublished" INTEGER,
    "language" TEXT NOT NULL DEFAULT 'it',
    "pageCount" INTEGER,
    "rating" REAL,
    "location" TEXT,
    "dateStarted" DATETIME,
    "dateFinished" DATETIME,
    "currentPage" INTEGER,
    "notes" TEXT,
    "category" TEXT,
    "wishList" BOOLEAN NOT NULL DEFAULT false,
    "previouslyOwned" BOOLEAN NOT NULL DEFAULT false,
    "upNext" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
